<?php

/**
 * @file
 * Install file for recruit_application_test.module.
 */

/**
 * Implements hook_install().
 */
function recruit_application_test_install() {

  // Create management application type.
  $type = entity_create('recruit_application_type', array(
    'type' => 'management',
    'label' => st('Management'),
  ));
  // Create application type.
  $type->save();

  // Create a job node.
  $types = array(
    array(
      'type' => 'recruit_test_job',
      'name' => st('Job'),
      'base' => 'node_content',
      'description' => st('Use <em>jobs</em> for testing jobs.'),
      'custom' => 1,
      'modified' => 1,
      'locked' => 0,
    ),
  );

  foreach ($types as $type) {
    $type = node_type_set_defaults($type);
    node_type_save($type);
    node_add_body_field($type);
  }

  // Define new fields.
  $fields = array(
    array(
      'field_name' => 'field_app_test_other',
      'type' => 'text_long',
    ),
    array(
      'field_name' => 'field_node_app',
      'type' => 'recruit_application_reference',
    ),
    array(
      'field_name' => 'field_cv',
      'type' => 'file',
      'cardinality' => 1,
      'settings' => array(
        'display_field' => 0,
        'display_default' => 0,
        'uri_scheme' => 'public',
      ),
    ),
  );
  
  // Create fields.
  foreach($fields as $field) {
    field_create_field($field);
  }


  $instances = array(
    array(
      'field_name' => 'field_app_test_other',
      'entity_type' => 'recruit_application',
      'bundle' => 'application',
      'label' => st('Other details'),
      'widget' => array('type' => 'text_textarea'),
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'type' => 'text_default',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'type' => 'text_default',
        ),
      ),
    ),
    array(
      'field_name' => 'field_node_app',
      'entity_type' => 'node',
      'bundle' => 'recruit_test_job',
      'label' => st('Application'),
      'widget' => array('type' => 'recruit_application_reference_select_list'),
      'display' => array(
        'default' => array(
          'label' => 'above',
          'type' => 'recruit_application_reference_link',
        ),
        'teaser' => array(
          'label' => 'above',
          'type' => 'recruit_application_reference_link',
        ),
      ),
    ),
    array(
      'field_name' => 'field_cv',
      'entity_type' => 'recruit_application',
      'bundle' => 'application',
      'label' => st('Upload CV'),
      'widget' => array('type' => 'file_generic'),
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'type' => 'file_default',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'type' => 'file_default',
        ),
      ),
    ),
  );

  foreach($instances as $instance) {
    field_create_instance($instance);
  }
}