<?php

/**
 * @file
 * Defines recruit_application entity.
 */

/**
 * Implements hook_menu().
 */
function recruit_application_menu() {
  $items = array();

  $items['node/%node/submit-application'] = array(
    'title' => 'Submit application',
    'page callback' => 'recruit_application_add_page',
    'page arguments' => array(1),
    'access callback' => 'recruit_application_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('create', NULL, 1),
    'file' => 'includes/recruit_application.pages.inc',
  );
  
  $items['recruit/application/%recruit_application'] = array(
    'title callback' => 'recruit_application_title',
    'title arguments' => array(2),
    'page callback' => 'recruit_application_view_page',
    'page arguments' => array(2),
    'access callback' => 'recruit_application_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('view', 2),
    'type' => MENU_CALLBACK,
    'file' => 'includes/recruit_application.pages.inc',
  );

  $items['recruit/application/%recruit_application/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
  $items['recruit/application/%recruit_application/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'recruit_application_edit_page',
    'page arguments' => array(2),
    'access callback' => 'recruit_application_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('update', 2),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/recruit_application.pages.inc',
  );
  
  $items['recruit/application/%recruit_application/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recruit_application_delete_confirm', 2),
    'access callback' => 'recruit_application_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('update', 2),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function recruit_application_entity_info() {
  $return =  array(
    'recruit_application' => array(
      'label' => t('Application'),
      'entity class' => 'RecruitApplication',
      'controller class' => 'RecruitApplicationEntityAPIController',      
      'base table' => 'recruit_application',
      'uri callback' => 'recruit_application_uri',
      //'access callback' => 'recruit_application_access',
      'metadata controller class' => 'RecruitApplicationMetadataController',
      'module' => 'recruit_application',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'aid',
        'bundle' => 'node_type',
        'label' => 'aid',
      ),
      'bundles' => array(),
      'view modes' => array(
        'full' => array(
          'label' => t('Full application'),
          'custom settings' => FALSE,
        ),
      ),
      'static cache' => FALSE,
    ),
  );

  foreach (node_type_get_names() as $type => $name) {
    $return['recruit_application']['bundles']['recruit_application_node_' . $type] = array(
      'label' => t('@node_type application', array('@node_type' => $name)),
      'admin' => array(
        'path' => 'admin/structure/types/manage/%recruit_application_node_type/application',
        'bundle argument' => 4,
        'real path' => 'admin/structure/types/manage/' . str_replace('_', '-', $type) . '/application',
        'access arguments' => array('administer content types'),
      ),
    );
  }

  return $return;
}

/**
 * Determines whether the given user has access to a application.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $application
 *   Optionally a application or a application type o check access for. If nothing is
 *   given, access for all applications is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function recruit_application_access($op, $application = NULL, $node = NULL, $account = NULL) {
  global $user;
  $account = isset($account) ? $account : $user;

  if (user_access('administer applications', $account)) {
    return TRUE;
  }

  if ($op == 'view' && user_access('access applications', $account)) {
    return TRUE;
  }

  if ($op == 'view' && $account->uid && user_access('view own ' . $application->node_type . ' application', $account) && $application->uid == $account->uid) {
    return TRUE;
  }
    
  if (isset($node) && is_object($node) && $op == 'create' && user_access('create recruit_application_node_' . $node->type . ' application', $account)) {
    return TRUE;
  }

  if (isset($application) && ($op == 'update' || $op == 'delete')) {
    if (user_access('edit any ' . $application->node_type . ' application', $account)) {
      return TRUE;
    }

    // Others either don't have any access or must match the application uid.
    if ($account->uid && user_access('edit own ' . $application->node_type . ' application', $account) && $application->uid == $account->uid) {
      return TRUE;
    }    
  }

  return FALSE;
}

/**
 * Implements hook_permission().
 */
function recruit_application_permission() {
  $permissions = array(
    'administer applications' =>  array(
      'title' => t('Administer applications'),
      'description' => t('Edit and view all applications.'),
    ),
    'access applications' => array(
      'title' => t('Access applications'),
      'description' => t('Allows users to view lists of applications in the administration section.'),
    ),
  );
  // Generate per application type permissions.
  foreach (node_type_get_types() as $type) {
    $type_name = 'recruit_application_node_' . check_plain($type->type);
    if (variable_get('recruit_' . $type->type, RECRUIT_DISABLED)) {
      $permissions += array(
        "create $type_name application" => array(
          'title' => t('%type_name: create application', array('%type_name' => $type->name)),
        ),
        "view own $type_name application" => array(
          'title' => t('%type_name: View own application', array('%type_name' => $type->name)),
        ),        
        "edit own $type_name application" => array(
          'title' => t('%type_name: Edit own application', array('%type_name' => $type->name)),
        ),
        "edit any $type_name application" => array(
          'title' => t('%type_name: Edit any application', array('%type_name' => $type->name)),
        ),
      );
    }
  }
  return $permissions;
}

/**
 * Implements hook_forms().
 */
function recruit_application_forms() {
  $forms = array();
  foreach (node_type_get_types() as $type) {
    $forms["recruit_application_node_" . $type->type . "_form"]['callback'] = 'recruit_application_application_form';
  }
  return $forms;
}

function recruit_application_application_form($form, &$form_state, $application) {
  $form = array();
  
  // Add the field related form elements.
  $form_state['recruit_application'] = $application;
  field_attach_form('recruit_application', $application, $form, $form_state);

  $form['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );
  // We add the form's #submit array to this button along with the actual submit
  // handler to preserve any submit handlers added by a form callback_wrapper.
  $submit = array();

  if (!empty($form['#submit'])) {
    $submit += $form['#submit'];
  }

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save application'),
    '#submit' => $submit + array('recruit_application_application_form_submit'),
  );

  $form['actions']['submit']['#suffix'] = l('Cancel', 'node/' . $application->nid);

  // We append the validate handler to #validate in case a form callback_wrapper
  // is used to add validate handlers earlier.
  $form['#validate'][] = 'recruit_application_application_form_validate';

  return $form;
}

/**
 * Validation callback for recruit_application_form().
 */
function recruit_application_application_form_validate($form, &$form_state) {
  $application = $form_state['recruit_application'];
  
  // Notify field widgets to validate their data.
  field_attach_form_validate('recruit_application', $application, $form, $form_state);
}

/**
 * Submit callback for recruit_application_form().
 */
function recruit_application_application_form_submit($form, &$form_state) {
  $application = $form_state['recruit_application'];

  // Notify field widgets.
  field_attach_submit('recruit_application', $application, $form, $form_state);

  // Save application.
  recruit_application_save($application);
  
  drupal_set_message(t('Application saved.'));
  drupal_goto('node/' . $application->nid);
}

/**
 * Form bulder; Asks for confirmation of application deletion.
 */
function recruit_application_delete_confirm($form, &$form_state, $application) {
  $form['#application'] = $application;
  $node = node_load($application->nid);
  $form['#node'] = $node;
  // Always provide entity id in the same form key as in the entity edit form.
  $form['aid'] = array('#type' => 'value', '#value' => $application->aid);
  return confirm_form($form,
    t('Are you sure you want to delete this application for %title job?', array('%title' => $node->title)),
    'recruit/application/' . $application->aid,
    t('This action cannot be undone.'),
    t('Delete'),
    t('Cancel')
  );
}

/**
 * Executes application deletion.
 */
function recruit_application_delete_confirm_submit($form, &$form_state) {
  if ($form_state['values']['confirm']) {
    $application = recruit_application_load($form_state['values']['aid']);
    $node = $form['#node'];
    
    recruit_application_delete($form_state['values']['aid']);

    watchdog('recruit_application', 'Application deleted for %title job.', array('%title' => $node->title));
    drupal_set_message(t('Application for %title has been deleted.', array('%title' => $node->title)));
  }

  $form_state['redirect'] = '<front>';
}

function recruit_application_get_node($nid) {
  return node_load($nid);
}

function recruit_application_title($application) {
  $node = recruit_application_get_node($application->nid);
  return t('Application for !title', array('!title' => check_plain($node->title)));
}

/**
 * Implements hook_menu_alter().
 */
function recruit_application_menu_alter(&$items) {
  // Adjust the Field UI tabs on admin/structure/types/manage/[node-type].
  // See recruit_entity_info().
  $items['admin/structure/types/manage/%recruit_application_node_type/application/fields']['title'] = 'Application fields';
  $items['admin/structure/types/manage/%recruit_application_node_type/application/fields']['weight'] = 5;
  $items['admin/structure/types/manage/%recruit_application_node_type/application/display']['title'] = 'Application display';
  $items['admin/structure/types/manage/%recruit_application_node_type/application/display']['weight'] = 6;
}

/**
 * Menu loader callback for Field UI paths.
 *
 * Return a application bundle name from a node type in the URL.
 */
function recruit_application_node_type_load($name) {
  if ($type = node_type_get_type(strtr($name, array('-' => '_')))) {
    return 'recruit_application_node_' . $type->type;
  }
}

/**
 * Create empty application object.
 * It's better to use recruit_application_new();
 *
 * @param $values
 *   You must pass $values array even if it's empty.
 *   Example:
 *   recruit_application_create(array('first_name' => '', 'last_name' => '', 'status' => 1, 'type' => $type));
 *   or
 *   recruit_application_create(array());
 *
 * @return
 *   Empty application object.
 */
function recruit_application_create(array $values) {
  return new RecruitApplication($values);
}

/**
 * Returns an initialized application object.
 *
 * @param $type
 *   The machine-readable type of the application.
 *
 * @return
 *   A application object with all default fields initialized.
 */
function recruit_application_new($node) {

  $values = array(
    'aid' => '',
    'nid' => $node->nid,
    'node_type' => 'recruit_application_node_' . $node->type,
    'created' => '',
    'changed' => '',
    'status' => 1,    
  );
  
  return new RecruitApplication($values);
}

/**
 * Fetch a application object.
 *
 * @param $aid
 *   Integer specifying the application id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $application object or FALSE if it cannot be loaded.
 *
 * @see recruit_application_load_multiple()
 */
function recruit_application_load($aid, $reset = FALSE) {
  $applications = recruit_application_load_multiple(array($aid), array(), $reset);
  return reset($applications);
}

/**
 * Load multiple applications based on certain conditions.
 *
 * @param $aids
 *   An array of application IDs.
 * @param $conditions
 *   An array of conditions to match against the {recruit_application} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of application objects, indexed by pid.
 *
 * @see entity_load()
 * @see recruit_application_load()
 */
function recruit_application_load_multiple($aids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('recruit_application', $aids, $conditions, $reset);
}

/**
 * Saves a application to the database.
 *
 * @param $application
 *   The application object.
 */
function recruit_application_save(RecruitApplication $application) {
  return $application->save();
}

/**
 * Deletes a application.
 */
function recruit_application_delete(RecruitApplication $application) {
  $application->delete();
}

/**
 * Delete multiple applications.
 *
 * @param $aids
 *   An array of application IDs.
 */
function recruit_application_delete_multiple(array $aids) {
  entity_get_controller('recruit_application')->delete($aids);
}

/**
 * Default uri callback.
 *
 * @see RecruitApplication::uri()
 */
function recruit_application_uri($application) {
  return array(
    'path' => 'recruit-application/' . $application->aid,
  );
}

/**
 * Implements hook_node_view_alter().
 */
function recruit_application_node_view_alter(&$build) {  
  $node = $build['#node'];
  if ($node->recruit == RECRUIT_ENABLED) {
    $links = recruit_application_links($node);
    $build['links']['recruit_application'] = array(
      '#theme' => 'links__node__recruit_application',
      '#links' => $links,
      '#attributes' => array('class' => array('links', 'inline')),
    );
  }
}

/**
 * Helper function used to build links.
 *
 * @param $node
 *   The node the application is attached to.
 * @return
 *   A structured array of links.
 */
function recruit_application_links($node) {
  $links = array();
  
  if (recruit_application_access('create', NULL, $node)) {
    $links['recruit-application-submit'] = array(
      'title' => t('Submit application'),
      'href' => "node/". $node->nid . "/submit-application",
      'html' => TRUE,
    );    
  }

  
  return $links;
}

/**
 * Implement hook_views_api().
 */
function recruit_application_views_api($module, $api) {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'recruit_application') . '/includes/views',
  );
}

/**
 * Implements hook_node_type_insert().
 *
 * Creates a first and last name field for a node type created while the recruit_application module
 * is enabled. For node types created before the recruit_application module is enabled,
 * hook_modules_enabled() serves to create the first and last anme fields.
 *
 * @see recruit_application_modules_enabled()
 */
function recruit_application_node_type_insert($info) {
  _recruit_application_field_create($info, 'recruit_app_first_name', 'First name');
  _recruit_application_field_create($info, 'recruit_app_last_name', 'Last name');
}

/**
 * Implements hook_node_type_update().
 */
function recruit_application_node_type_update($info) {
  if (!empty($info->old_type) && $info->type != $info->old_type) {
    field_attach_rename_bundle('recruit_application', 'recruit_application_node_' . $info->old_type, 'recruit_application_node_' . $info->type);
  }
}

/**
 * Implements hook_node_type_delete().
 */
function recruit_application_node_type_delete($info) {
  field_attach_delete_bundle('recruit_application', 'recruit_application_node_' . $info->type);
}

 /**
  * Creates a first and last name field instance for a given node type.
  * 
  * @param $info
  *   Node type info.
  * @param $field_name
  *   Field name example: recruit_app_first_name
  * @param $field_label 
  *   Field label
  * 
  * @see recruit_application_node_type_insert()
  */
function _recruit_application_field_create($info, $field_name, $field_label) {
  // Create the field if needed.
  if (!field_read_field($field_name, array('include_inactive' => TRUE))) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'text',
      'entity_types' => array('recruit_application'),
    );
    field_create_field($field);
  }
  // Create the instance if needed.
  if (!field_read_instance('recruit_application', $field_name, 'recruit_application_node_' . $info->type, array('include_inactive' => TRUE))) {
    field_attach_create_bundle('recruit_application', 'recruit_application_node_' . $info->type);
    // Attaches the body field by default.
    $instance = array(
      'field_name' => $field_name,
      'label' => $field_label,
      'entity_type' => 'recruit_application',
      'bundle' => 'recruit_application_node_' . $info->type,
      'required' => TRUE,
    );
    field_create_instance($instance);
  }
}

/**
 * The class used for application entities.
 */
class RecruitApplication extends Entity {

  public function __construct($values = array()) {
    if (empty($this->uid)) {
      $this->setUser();
    }
    
    parent::__construct($values, 'recruit_application');
  }

  /**
   * Returns the user owning this application.
   */
  public function user() {
    return user_load($this->uid);
  }

  /**
   * Sets a new user owning this application.
   */
  public function setUser($account = NULL) {
    if (!empty($account)) {
      $this->uid = $account->uid;
    }
    else {
     $this->uid = $GLOBALS['user']->uid; 
    }
  }

  /**
   * Returns the URI for this application. May be altered via hook_entity_info().
   */
  public function uri() {
    return entity_uri('recruit_application', $this);
  }

  /**
   * Returns the full url() for the application.
   */
  public function url() {
    $uri = $this->uri();
    return url($uri['path'], $uri);
  }

  /**
   * Returns the drupal path to this application.
   */
  public function path() {
    $uri = $this->uri();
    return $uri['path'];
  }

  /**
   * Returns parent save method.
   */
  public function save() {
    //Always set changed time when saving a application.
    $this->changed = REQUEST_TIME;
    
    //If this is a new application.
    if (empty($this->aid)) {
      $this->created = REQUEST_TIME;
    }
    
    return parent::save();
  }
}

class RecruitApplicationEntityAPIController extends EntityAPIController {
  protected function attachLoad(&$applications, $revision_id = FALSE) {
    
    // Setup standard application properties.
    foreach ($applications as $key => $application) {
      // $application->new = node_mark($application->nid, $application->changed);
      $application->node_type = 'recruit_application_node_' . $application->node_type;
      $applications[$key] = $application;
    }
    parent::attachLoad($applications, $revision_id);
  }

  protected function buildQuery($ids, $conditions = array(), $revision_id = FALSE) {
    $query = parent::buildQuery($ids, $conditions, $revision_id);
    // Specify additional fields from the user and node tables.
    $query->innerJoin('node', 'n', 'base.nid = n.nid');
    $query->addField('n', 'type', 'node_type');
    $query->innerJoin('users', 'u', 'base.uid = u.uid');
    return $query;
  }
}




