<?php



/**
 * Implements hook_menu().
 */
function recruit_application_menu() {
  $items = array();

  $items['recruit/apply/%node'] = array(
    'title' => 'Submit application',
    'page callback' => 'recruit_application_add_page',
    'page arguments' => array(2),
    'access callback' => 'node_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('view', 2),
    'file' => 'includes/recruit_application.pages.inc',
  );
  
  $items['recruit/application/%recruit_application'] = array(
    'title callback' => 'recruit_application_title',
    'title arguments' => array(2),
    'page callback' => 'recruit_application_view_page',
    'page arguments' => array(2),
    'access callback' => 'node_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('view', 2),
    'type' => MENU_CALLBACK,
    'file' => 'includes/recruit_application.pages.inc',
  );

  $items['recruit/application/%recruit_application/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
  $items['recruit/application/%recruit_application/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'recruit_application_edit_page',
    'page arguments' => array(2),
    'access callback' => 'node_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('view', 2),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/recruit_application.pages.inc',
  );
  
  $items['recruit/application/%recruit_application/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('recruit_application_delete_confirm', 2),
    'access callback' => 'node_access', // TODO: create custom access function to stop users from changing the node id directly in URL>
    'access arguments' => array('view', 2),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function recruit_application_entity_info() {
  $return =  array(
    'recruit_application' => array(
      'label' => t('Application'),
      'entity class' => 'RecruitApplication',
      'controller class' => 'RecruitApplicationEntityAPIController',      
      'base table' => 'recruit_application',
      'uri callback' => 'recruit_application_uri',
      // 'access callback' => 'recruit_application_access',
      'module' => 'recruit_application',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'aid',
        'bundle' => 'node_type',
        'label' => 'aid',
      ),
      'bundles' => array(),
      'view modes' => array(
        'full' => array(
          'label' => t('Full application'),
          'custom settings' => FALSE,
        ),
      ),
      'static cache' => FALSE,
    ),
  );

  foreach (node_type_get_names() as $type => $name) {
    $return['recruit_application']['bundles']['recruit_application_node_' . $type] = array(
      'label' => t('@node_type application', array('@node_type' => $name)),
      'admin' => array(
        'path' => 'admin/structure/types/manage/%recruit_application_node_type/application',
        'bundle argument' => 4,
        'real path' => 'admin/structure/types/manage/' . str_replace('_', '-', $type) . '/application',
        'access arguments' => array('administer content types'),
      ),
    );
  }

  return $return;
}

/**
 * Implements hook_forms().
 */
function recruit_application_forms() {
  $forms = array();
  foreach (node_type_get_types() as $type) {
    $forms["recruit_application_node_" . $type->type . "_form"]['callback'] = 'recruit_application_application_form';
  }
  return $forms;
}

function recruit_application_application_form($form, &$form_state, $application) {
  $form = array();
  
  // Add the field related form elements.
  $form_state['recruit_application'] = $application;
  field_attach_form('recruit_application', $application, $form, $form_state);

  $form['actions'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('form-actions')),
    '#weight' => 400,
  );
  // We add the form's #submit array to this button along with the actual submit
  // handler to preserve any submit handlers added by a form callback_wrapper.
  $submit = array();

  if (!empty($form['#submit'])) {
    $submit += $form['#submit'];
  }

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save application'),
    '#submit' => $submit + array('recruit_application_application_form_submit'),
  );

  // We append the validate handler to #validate in case a form callback_wrapper
  // is used to add validate handlers earlier.
  $form['#validate'][] = 'recruit_application_application_form_validate';

  return $form;
}

/**
 * Validation callback for recruit_application_form().
 */
function recruit_application_application_form_validate($form, &$form_state) {
  $application = $form_state['recruit_application'];
  
  // Notify field widgets to validate their data.
  field_attach_form_validate('recruit_application', $application, $form, $form_state);
}

/**
 * Submit callback for recruit_application_form().
 */
function recruit_application_application_form_submit($form, &$form_state) {
  $application = $form_state['recruit_application'];

  // Notify field widgets.
  field_attach_submit('recruit_application', $application, $form, $form_state);

  // Save application.
  recruit_application_save($application);

  drupal_set_message(t('Application saved.'));
}

/**
 * Form bulder; Asks for confirmation of application deletion.
 */
function recruit_application_delete_confirm($form, &$form_state, $application) {
  $form['#application'] = $application;
  $node = node_load($application->nid);
  $form['#node'] = $node;
  // Always provide entity id in the same form key as in the entity edit form.
  $form['aid'] = array('#type' => 'value', '#value' => $application->aid);
  return confirm_form($form,
    t('Are you sure you want to delete this application for %title job?', array('%title' => $node->title)),
    'recruit/application/' . $application->aid,
    t('This action cannot be undone.'),
    t('Delete'),
    t('Cancel')
  );
}

/**
 * Executes application deletion.
 */
function recruit_application_delete_confirm_submit($form, &$form_state) {
  if ($form_state['values']['confirm']) {
    $application = recruit_application_load($form_state['values']['aid']);
    $node = $form['#node'];
    
    recruit_application_delete($form_state['values']['aid']);

    watchdog('recruit_application', 'Application deleted for %title job.', array('%title' => $node->title));
    drupal_set_message(t('Application for %title has been deleted.', array('%title' => $node->title)));
  }

  $form_state['redirect'] = '<front>';
}

function recruit_application_get_node($nid) {
  return node_load($nid);
}

function recruit_application_title($application) {
  $node = recruit_application_get_node($application->nid);
  return t('Application for !title', array('!title' => check_plain($node->title)));
}

/**
 * Implements hook_menu_alter().
 */
function recruit_application_menu_alter(&$items) {
  // Adjust the Field UI tabs on admin/structure/types/manage/[node-type].
  // See recruit_entity_info().
  $items['admin/structure/types/manage/%recruit_application_node_type/application/fields']['title'] = 'Application fields';
  $items['admin/structure/types/manage/%recruit_application_node_type/application/fields']['weight'] = 5;
  $items['admin/structure/types/manage/%recruit_application_node_type/application/display']['title'] = 'Application display';
  $items['admin/structure/types/manage/%recruit_application_node_type/application/display']['weight'] = 6;
}

/**
 * Menu loader callback for Field UI paths.
 *
 * Return a application bundle name from a node type in the URL.
 */
function recruit_application_node_type_load($name) {
  if ($type = node_type_get_type(strtr($name, array('-' => '_')))) {
    return 'recruit_application_node_' . $type->type;
  }
}

/**
 * Create empty application object.
 * It's better to use recruit_application_new();
 *
 * @param $values
 *   You must pass $values array even if it's empty.
 *   Example:
 *   recruit_application_create(array('first_name' => '', 'last_name' => '', 'status' => 1, 'type' => $type));
 *   or
 *   recruit_application_create(array());
 *
 * @return
 *   Empty application object.
 */
function recruit_application_create(array $values) {
  return new RecruitApplication($values);
}

/**
 * Returns an initialized application object.
 *
 * @param $type
 *   The machine-readable type of the application.
 *
 * @return
 *   A application object with all default fields initialized.
 */
function recruit_application_new($node) {

  $values = array(
    'aid' => '',
    'nid' => $node->nid,
    'node_type' => 'recruit_application_node_' . $node->type,
    'uid' => '',
    'created' => '',
    'changed' => '',
    'status' => 1,    
  );
  
  return new RecruitApplication($values);
}

/**
 * Fetch a application object.
 *
 * @param $aid
 *   Integer specifying the application id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $application object or FALSE if it cannot be loaded.
 *
 * @see recruit_application_load_multiple()
 */
function recruit_application_load($aid, $reset = FALSE) {
  $applications = recruit_application_load_multiple(array($aid), array(), $reset);
  return reset($applications);
}

/**
 * Load multiple applications based on certain conditions.
 *
 * @param $aids
 *   An array of application IDs.
 * @param $conditions
 *   An array of conditions to match against the {recruit_application} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of application objects, indexed by pid.
 *
 * @see entity_load()
 * @see recruit_application_load()
 */
function recruit_application_load_multiple($aids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('recruit_application', $aids, $conditions, $reset);
}

/**
 * Saves a application to the database.
 *
 * @param $application
 *   The application object.
 */
function recruit_application_save(RecruitApplication $application) {
  return $application->save();
}

/**
 * Deletes a application.
 */
function recruit_application_delete(RecruitApplication $application) {
  $application->delete();
}

/**
 * Delete multiple applications.
 *
 * @param $aids
 *   An array of application IDs.
 */
function recruit_application_delete_multiple(array $aids) {
  entity_get_controller('recruit_application')->delete($aids);
}

/**
 * Default uri callback.
 *
 * @see RecruitApplication::uri()
 */
function recruit_application_uri($application) {
  return array(
    'path' => 'recruit-application/' . $application->aid,
  );
}

/**
 * The class used for application entities.
 */
class RecruitApplication extends Entity {

  public function __construct($values = array()) {
    if (isset($values['user'])) {
      $this->setUser($values['user']);
      unset($values['user']);
    }
    parent::__construct($values, 'recruit_application');
  }

  /**
   * Returns the user owning this application.
   */
  public function user() {
    return user_load($this->uid);
  }

  /**
   * Sets a new user owning this application.
   */
  public function setUser($account) {
    $this->uid = $account->uid;
  }

  /**
   * Returns the URI for this application. May be altered via hook_entity_info().
   */
  public function uri() {
    return entity_uri('recruit_application', $this);
  }

  /**
   * Returns the full url() for the application.
   */
  public function url() {
    $uri = $this->uri();
    return url($uri['path'], $uri);
  }

  /**
   * Returns the drupal path to this application.
   */
  public function path() {
    $uri = $this->uri();
    return $uri['path'];
  }

  /**
   * Returns parent save method.
   */
  public function save() {
    //Always set changed time when saving a application.
    $this->changed = REQUEST_TIME;
    
    //If this is a new application.
    if (empty($this->application_id)) {
      $this->created = REQUEST_TIME;
    }
    
    return parent::save();
  }
}

class RecruitApplicationEntityAPIController extends EntityAPIController {
  protected function attachLoad(&$applications, $revision_id = FALSE) {
    
    // Setup standard application properties.
    foreach ($applications as $key => $application) {
      // $application->new = node_mark($application->nid, $application->changed);
      $application->node_type = 'recruit_application_node_' . $application->node_type;
      $applications[$key] = $application;
    }
    parent::attachLoad($applications, $revision_id);
  }

  protected function buildQuery($ids, $conditions = array(), $revision_id = FALSE) {
    $query = parent::buildQuery($ids, $conditions, $revision_id);
    // Specify additional fields from the user and node tables.
    $query->innerJoin('node', 'n', 'base.nid = n.nid');
    $query->addField('n', 'type', 'node_type');
    $query->innerJoin('users', 'u', 'base.uid = u.uid');
    return $query;
  }
}




