<?php

/**
 * @file
 * Global recruit module.
 */

 /**
 * Enable job posting
 */
define('RECRUIT_ENABLED', 1);
define('RECRUIT_DISABLED', 0);

/**
 * Implements hook_menu().
 */
function recruit_menu() {
  $items = array();

  $items['admin/recruit'] = array(
    'title' => 'Recruit',
    'description' => 'Administer your jobs and applications.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access recruit administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
  /*
  $items['admin/recruit/config'] = array(
    'title' => 'Configuration',
    'description' => 'Configure settings for your recruitment site.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
   *
   */
  return $items;
}

function recruit_add_job_field($type, $label = 'Job') {
  $field = field_info_field('recruit_job');
  $instance = field_info_instance('node', 'recruit_job', $type->type);
  if (empty($field)) {
    $field = array(
      'field_name' => 'recruit_job',
      'type' => 'recruit_job',
      'entity_types' => array('node'),
    );
    $field = field_create_field($field);
  }
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'recruit_job',
      'entity_type' => 'node',
      'bundle' => $type->type,
      'label' => $label,
      'widget' => array('type' => 'recruit_job_default'),
      'settings' => array(),
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'type' => 'recruit_job_default',
        ),
      ),
    );
    $instance = field_create_instance($instance);
  }
  return $instance;
}
