<?php

/**
 * @file
 * Exposes recruit_application.module fields to views.
 */

/**
 * Export Recruit applications to Views.
 */

/**
 * Implements hook_views_data_alter()
 * EntityAPI implements hook_views_data for the recruit_application.
 * 
 * Entity API handles a lot of the relationship handling with EntityDefaultMetadataController.
 */
function recruit_application_views_data_alter(&$data) {
}